services:
  sqlserver-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ims_sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DB_PASS}
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/mssql
      - ./script.sql:/script.sql
    networks:
      - app-network

  webapp:
    build: . # Build từ Dockerfile ở thư mục hiện tại
    image: ims_webapp
    container_name: ims_webapp
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/usr/local/tomcat/.env
    networks:
      - app-network

volumes:
  sqlserver-data:

networks:
  app-network:
    driver: bridge